### ISSUE TITLE
Feature Request Summary - Exceeds Expectations

### ISSUE THREAD

**Issue by jlag34** [calikat625/jammming-feature-request#1]
You did a great job with your feature request! Don't think I've seen anyone introduce a feature with cookies. In my opinion, people are fading out cookie usage for `localStore`, located on the `window` property. You can run CRUD operations there to store any local data. Awesome job doing extra work to figure that out (or maybe you have previous knowledge?). Also, great job with your other features, resetting the app and the styles. You added just enough code to your technical design that I feel like I could easily implement these features. Lastly, good work adding caveats and covering your edges cases and bringing up possible problems. All in all, you did an excellent job on this project and displayed characteristics of true software engineer.

**Comment by calikat625** [comment]
Thank you @jlag34 for taking the time to review. I was actually worried that I could have done more. Appreciate the constructive and supportive feedback.
